### ISSUE TITLE
Demo - problem with heights

### ISSUE THREAD

**Issue by xenongattz** [dashersw/pedalboard.js#15]
Found the bug on this page: http://dashersw.github.io/pedalboard.js/demo/

Screenshot here:
https://yadi.sk/i/toHJKyfFtP6RF

Problem actual for latest (at time of writing this issue) version of Chrome (including Canary) and Opera. Looks good in Safari and Mozilla.

**Comment by dashersw** [comment]
Thanks for the report @xenongattz, I will look into it in the weekend.
