### ISSUE TITLE
 How Can I get the output blob of an audio file when apply some effect?

### ISSUE THREAD

**Issue by cesarodriguez4** [dashersw/pedalboard.js#17]
I want to get the output blob of a specific arrange of the pedals, how can I do that? I don't see any method that make that function (extract/export the blob), is that possible?

**Comment by adamfr33man** [comment]
@cesarodriguez4 Do you mean being able to start/stop recording and download a WAV/MP3 file or something like that ?

**Comment by cesarodriguez4** [comment]
Well, something similar than that you say, not in real time, but using a external sound file. In example: browse an audio file in your directory, and then press a button for proccess/download a file with all effects of the pedals inside.

![screenshot from 2016-12-04 20 30 03](https://cloud.githubusercontent.com/assets/11139209/20870535/88ad5a44-ba60-11e6-87ae-bf2d50024b9c.png)

**Comment by adamfr33man** [comment]
Oh, I see what you mean, so you can save/load pedal configurations. I know you could load/save boards if you logged into https://pedals.io/ but I just tried it and got 504d. Could probably add this functionality but not too sure how easy it would be, I don't think there is an easy JSON objext to import/export.

**Comment by cesarodriguez4** [comment]
Well... let me explain better, not is the configuration file as it, It's just the sound file applying that configuration. pedalboard just have the option for listen an audio file with some effects but no to download it, I want the option for download the file with the effects processed.
