### ISSUE TITLE
[Demo] Chrome does not allow insecure sites to access the mic.

### ISSUE THREAD

**Issue by carlsmith** [dashersw/pedalboard.js#23]
The demo site cannot access the user's microphone in Chrome unless its over HTTPS.

When you click on the **Line-In** link, nothing seems to happen, but looking at the console, it causes an `Uncaught Error` in `compiled.js` at Line 585: *SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)*.

That link expands to `www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features`.

I manually changed the URL to start with HTTPS, and everything works fine, but the link in the README uses HTTP, and it's not obvious to users why it then doesn't work.

Adding a note telling users to ensure they're using HTTPS would work, but it should be fairly easy to detect the protocol and redirect the user to the secure version with clientside JS.

**Comment by dashersw** [comment]
Thank you for the issue and the fix!
